---
roles:
  - src: geerlingguy.nodejs
  - src: inverse_inc.gitlab_buildpkg_tools

collections:
  - name: inverse_inc.packetfence
    version: 1.0.1
  - name: debops.debops
  - name: inverse_inc.windows
  - name: inverse_inc.cumulus

